-- SI deberia funcionar
USE GestionSeguridadCode
GO

DECLARE @RC int

DECLARE @TIPO	INT
DECLARE @FECHA datetime
DECLARE @DETALLE VARCHAR(500)
DECLARE @LUGAR VARCHAR(10)
DECLARE @DETALLE_EMPLEADO varchar(500)
DECLARE @EMPLEADO_ID INT
DECLARE @ACCIDENTE_ID INT

EXECUTE @RC = [dbo].[REGISTRAR_ACCIDENTE] 
    @TIPO = "A",
	@FECHA = "21/09/2018",
	@DETALLE = "****",
	@LUGAR =  "COCHABAMBA",
	@DETALLE_EMPLEADO = "****",
	@EMPLEADO_ID = 12354,
	@ACCIDENTE_ID = 12
GO

--NO funciona
-----------------------------------------------
DECLARE @RC int

DECLARE @NOMBRES VARCHAR(50)
DECLARE @APELLIDOS	VARCHAR(50)
DECLARE @TELEFONO VARCHAR(25)
DECLARE @DIRECCION VARCHAR(200)
DECLARE @EMAIL VARCHAR(25)
DECLARE @SEXO CHAR(2)
DECLARE @NACIMIENTO DATETIME
DECLARE @CI	VARCHAR(15)
DECLARE @NACIONALIDAD VARCHAR(25)
DECLARE @PERSONA_ID INT

EXECUTE @RC = [dbo].[INSERT_PERSON] 

    @NOMBRES = 'Pamela'
	,@APELLIDOS = 'Arnez'
	,@TELEFONO = '78456641'
	,@DIRECCION = 'Urbanizacion Flores'
	,@EMAIL = 'wen@gmail.com'
	,@SEXO = 'F'
	,@NACIMIENTO = '20/12/1992'
	,@CI = 5464654
	,@NACIONALIDAD = 'Bol'
	,@PERSONA_ID = 5468465
GO